---
# backups
# to-do: Do not try to copy files we've already copied.
- name: Backup files that are to be changed.
  copy:
      remote_src: yes
      backup: yes
      dest: "{{ chsec_backupdir }}/{{ item.file | basename }}.{{ ansible_date_time.iso8601_basic_short }}" 
      src: "{{ item.file }}"
  when: 
    - chsec_backup|bool
  loop: "{{ chsec }}"

- name: Debug chsec contents
  debug:
    var: chsec
    verbosity: 2

- name: Run chsec commands.
  # Find local_aix_chsec in ../library/local_aix_chsec.py
  # I've named it local_* in case the pull request ever gets accepted and we dont step on the 'official' chsec role'
  local_aix_chsec:
    path: "{{ item.file }}"
    stanza: "{{ item.stanza }}"
    attrs: " {{ item.attrs }}"
    state: present
  loop: "{{ chsec }}"
  when:
    - item.file in chsec_managed_files
